# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/LabelManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabelManager(object):
    def setupUi(self, LabelManager):
        LabelManager.setObjectName("LabelManager")
        LabelManager.resize(242, 233)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LabelManager.sizePolicy().hasHeightForWidth())
        LabelManager.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(LabelManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout = QtWidgets.QHBoxLayout()
        self.layout.setObjectName("layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(LabelManager)
        self.addButton.setObjectName("addButton")
        self.layout.addWidget(self.addButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout.addItem(spacerItem1)
        self.removeButton = QtWidgets.QPushButton(LabelManager)
        self.removeButton.setEnabled(False)
        self.removeButton.setObjectName("removeButton")
        self.layout.addWidget(self.removeButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.layout)
        self.list = QtWidgets.QListWidget(LabelManager)
        self.list.setMinimumSize(QtCore.QSize(220, 180))
        self.list.setObjectName("list")
        self.verticalLayout.addWidget(self.list)

        self.retranslateUi(LabelManager)
        self.addButton.clicked.connect(LabelManager.create)
        self.list.itemClicked['QListWidgetItem*'].connect(LabelManager.displayLabelPanel)
        self.removeButton.clicked.connect(LabelManager.remove)
        QtCore.QMetaObject.connectSlotsByName(LabelManager)

    def retranslateUi(self, LabelManager):
        _translate = QtCore.QCoreApplication.translate
        LabelManager.setWindowTitle(_translate("LabelManager", "Form"))
        self.addButton.setText(_translate("LabelManager", "Add"))
        self.removeButton.setText(_translate("LabelManager", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabelManager = QtWidgets.QWidget()
    ui = Ui_LabelManager()
    ui.setupUi(LabelManager)
    LabelManager.show()
    sys.exit(app.exec_())
