# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainApplication.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainApplication(object):
    def setupUi(self, MainApplication):
        MainApplication.setObjectName("MainApplication")
        MainApplication.resize(584, 433)
        self.main = QtWidgets.QWidget(MainApplication)
        self.main.setObjectName("main")
        MainApplication.setCentralWidget(self.main)
        self.menubar = QtWidgets.QMenuBar(MainApplication)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainApplication.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainApplication)
        self.statusbar.setObjectName("statusbar")
        MainApplication.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainApplication)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainApplication)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainApplication)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainApplication)
        self.actionNew.triggered.connect(MainApplication.new)
        self.actionOpen.triggered.connect(MainApplication.open)
        self.actionExit.triggered.connect(MainApplication.exit)
        QtCore.QMetaObject.connectSlotsByName(MainApplication)

    def retranslateUi(self, MainApplication):
        _translate = QtCore.QCoreApplication.translate
        MainApplication.setWindowTitle(_translate("MainApplication", "MainWindow"))
        self.menuFile.setTitle(_translate("MainApplication", "File"))
        self.actionNew.setText(_translate("MainApplication", "New record"))
        self.actionOpen.setText(_translate("MainApplication", "Open record"))
        self.actionExit.setText(_translate("MainApplication", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainApplication = QtWidgets.QMainWindow()
    ui = Ui_MainApplication()
    ui.setupUi(MainApplication)
    MainApplication.show()
    sys.exit(app.exec_())
