# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainApplication.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainApplication(object):
    def setupUi(self, MainApplication):
        MainApplication.setObjectName("MainApplication")
        MainApplication.resize(1105, 748)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainApplication.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../icons/LogoApp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainApplication.setWindowIcon(icon)
        self.main = QtWidgets.QWidget(MainApplication)
        self.main.setObjectName("main")
        self.LogoSherbrooke = QtWidgets.QLabel(self.main)
        self.LogoSherbrooke.setGeometry(QtCore.QRect(20, 20, 291, 111))
        self.LogoSherbrooke.setText("")
        self.LogoSherbrooke.setPixmap(QtGui.QPixmap("ui\\../icons/universiteLogo.png"))
        self.LogoSherbrooke.setScaledContents(True)
        self.LogoSherbrooke.setObjectName("LogoSherbrooke")
        self.LogoGphy = QtWidgets.QLabel(self.main)
        self.LogoGphy.setGeometry(QtCore.QRect(890, 530, 131, 131))
        self.LogoGphy.setText("")
        self.LogoGphy.setPixmap(QtGui.QPixmap("ui\\../icons/LogoGphy.jpg"))
        self.LogoGphy.setScaledContents(True)
        self.LogoGphy.setObjectName("LogoGphy")
        MainApplication.setCentralWidget(self.main)
        self.menubar = QtWidgets.QMenuBar(MainApplication)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainApplication.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainApplication)
        self.statusbar.setObjectName("statusbar")
        MainApplication.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainApplication)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../icons/LogoBarre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainApplication)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\../icons/Open.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainApplication)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\../icons/Exit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainApplication)
        self.actionNew.triggered.connect(MainApplication.new)
        self.actionOpen.triggered.connect(MainApplication.open)
        self.actionExit.triggered.connect(MainApplication.exit)
        QtCore.QMetaObject.connectSlotsByName(MainApplication)

    def retranslateUi(self, MainApplication):
        _translate = QtCore.QCoreApplication.translate
        MainApplication.setWindowTitle(_translate("MainApplication", "MainWindow"))
        self.menuFile.setTitle(_translate("MainApplication", "File"))
        self.actionNew.setText(_translate("MainApplication", "New record"))
        self.actionOpen.setText(_translate("MainApplication", "Open record"))
        self.actionExit.setText(_translate("MainApplication", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainApplication = QtWidgets.QMainWindow()
    ui = Ui_MainApplication()
    ui.setupUi(MainApplication)
    MainApplication.show()
    sys.exit(app.exec_())
