# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecordSession.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordSession(object):
    def setupUi(self, RecordSession):
        RecordSession.setObjectName("RecordSession")
        RecordSession.resize(235, 99)
        self.gridLayout = QtWidgets.QGridLayout(RecordSession)
        self.gridLayout.setObjectName("gridLayout")
        self.recordButton = QtWidgets.QPushButton(RecordSession)
        self.recordButton.setObjectName("recordButton")
        self.gridLayout.addWidget(self.recordButton, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(RecordSession)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(RecordSession)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 2, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(RecordSession)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 1, 0, 1, 1)
        self.time = QtWidgets.QLabel(RecordSession)
        self.time.setEnabled(False)
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 0, 1, 1, 1)

        self.retranslateUi(RecordSession)
        self.recordButton.clicked.connect(RecordSession.start)
        self.stopButton.clicked.connect(RecordSession.stop)
        self.saveButton.clicked.connect(RecordSession.save)
        QtCore.QMetaObject.connectSlotsByName(RecordSession)

    def retranslateUi(self, RecordSession):
        _translate = QtCore.QCoreApplication.translate
        RecordSession.setWindowTitle(_translate("RecordSession", "Form"))
        self.recordButton.setText(_translate("RecordSession", "Enregistrer"))
        self.saveButton.setText(_translate("RecordSession", "Sauvegarder"))
        self.stopButton.setText(_translate("RecordSession", "Arrêter"))
        self.time.setText(_translate("RecordSession", "0:00"))
