# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/WindowsDevicePortal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowsDevicePortal(object):
    def setupUi(self, WindowsDevicePortal):
        WindowsDevicePortal.setObjectName("WindowsDevicePortal")
        WindowsDevicePortal.resize(355, 218)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WindowsDevicePortal.sizePolicy().hasHeightForWidth())
        WindowsDevicePortal.setSizePolicy(sizePolicy)
        WindowsDevicePortal.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(WindowsDevicePortal)
        self.gridLayout.setObjectName("gridLayout")
        self.batteryLabel = QtWidgets.QLabel(WindowsDevicePortal)
        self.batteryLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.batteryLabel.setObjectName("batteryLabel")
        self.gridLayout.addWidget(self.batteryLabel, 4, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.batteryLevel = QtWidgets.QLabel(WindowsDevicePortal)
        self.batteryLevel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.batteryLevel.setObjectName("batteryLevel")
        self.gridLayout.addWidget(self.batteryLevel, 4, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.passwordInput = QtWidgets.QLineEdit(WindowsDevicePortal)
        self.passwordInput.setText("")
        self.passwordInput.setObjectName("passwordInput")
        self.gridLayout.addWidget(self.passwordInput, 2, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(WindowsDevicePortal)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 2, 0, 1, 1)
        self.hostLabel = QtWidgets.QLabel(WindowsDevicePortal)
        self.hostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hostLabel.setObjectName("hostLabel")
        self.gridLayout.addWidget(self.hostLabel, 0, 0, 1, 1)
        self.hostInput = QtWidgets.QLineEdit(WindowsDevicePortal)
        self.hostInput.setText("")
        self.hostInput.setObjectName("hostInput")
        self.gridLayout.addWidget(self.hostInput, 0, 1, 1, 1)
        self.loginLabel = QtWidgets.QLabel(WindowsDevicePortal)
        self.loginLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.gridLayout.addWidget(self.loginLabel, 1, 0, 1, 1)
        self.loginInput = QtWidgets.QLineEdit(WindowsDevicePortal)
        self.loginInput.setAutoFillBackground(False)
        self.loginInput.setText("")
        self.loginInput.setObjectName("loginInput")
        self.gridLayout.addWidget(self.loginInput, 1, 1, 1, 1)
        self.previewLabel = QtWidgets.QLabel(WindowsDevicePortal)
        self.previewLabel.setObjectName("previewLabel")
        self.gridLayout.addWidget(self.previewLabel, 5, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.previewButton = QtWidgets.QPushButton(WindowsDevicePortal)
        self.previewButton.setEnabled(False)
        self.previewButton.setObjectName("previewButton")
        self.gridLayout.addWidget(self.previewButton, 5, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.previewInfo = QtWidgets.QLabel(WindowsDevicePortal)
        self.previewInfo.setText("")
        self.previewInfo.setObjectName("previewInfo")
        self.gridLayout.addWidget(self.previewInfo, 6, 1, 1, 1)
        self.connectButton = QtWidgets.QPushButton(WindowsDevicePortal)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout.addWidget(self.connectButton, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)

        self.retranslateUi(WindowsDevicePortal)
        self.connectButton.clicked.connect(WindowsDevicePortal.connection)
        self.previewButton.clicked.connect(WindowsDevicePortal.togglePreview)
        QtCore.QMetaObject.connectSlotsByName(WindowsDevicePortal)

    def retranslateUi(self, WindowsDevicePortal):
        _translate = QtCore.QCoreApplication.translate
        WindowsDevicePortal.setWindowTitle(_translate("WindowsDevicePortal", "Form"))
        self.batteryLabel.setText(_translate("WindowsDevicePortal", "Battery:"))
        self.batteryLevel.setText(_translate("WindowsDevicePortal", "/"))
        self.passwordLabel.setText(_translate("WindowsDevicePortal", "Password"))
        self.hostLabel.setText(_translate("WindowsDevicePortal", "Host"))
        self.loginLabel.setText(_translate("WindowsDevicePortal", "Login"))
        self.previewLabel.setText(_translate("WindowsDevicePortal", "Preview:"))
        self.previewButton.setText(_translate("WindowsDevicePortal", "On"))
        self.connectButton.setText(_translate("WindowsDevicePortal", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowsDevicePortal = QtWidgets.QWidget()
    ui = Ui_WindowsDevicePortal()
    ui.setupUi(WindowsDevicePortal)
    WindowsDevicePortal.show()
    sys.exit(app.exec_())
